language: php
sudo: false

php:
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit;

jobs:
  include:
    - stage: Test
      name: Dependency analyzer
      php: 7.2
      script:
        - ./vendor/bin/analyze-deps verify ./src 

