language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit;

jobs:
  include:
    - stage: Test
      name: Lowest dependencies
      php: 7.2
      install: composer update --prefer-dist --prefer-lowest

    - stage: Test
      name: Code coverage
      php: 7.2
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
      
    - stage: Code Quality
      name: Dependency analyer
      php: 7.2
      script:
        - ./vendor/bin/analyze-deps verify ./src --rule=./rule.php

  allow_failures:
    - php: nightly
